### ISSUE TITLE
Prevent display of username transferred to other address

### ISSUE THREAD

**Issue by albixhafa** [leather-io/extension#1551]
Hi, 

My wallet associated with address SPTCSBVXZ6KNV7JEMHAV7KJM9183VAP31053H0R4 t is showing the old btc domain (omg.btc) which I transferred to another address. Please see attached screenshot.
![unnamed](https://user-images.githubusercontent.com/55335339/128778277-d7324265-7517-4177-9c51-2279d15125d4.jpg)

**Comment by andresgalante** [comment]
Hi @baffledjet are you still experiencing this issue?

**Comment by albixhafa** [comment]
> Hi @baffledjet are you still experiencing this issue?

yes, its still displaying the old domain.

**Comment by fbwoolf** [comment]
@baffledjet can you update to the latest version of the wallet and see if it is still an issue?

**Comment by aulneau** [comment]
Hmm digging into this more, the api reports the original owner as the current owner: https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SPTCSBVXZ6KNV7JEMHAV7KJM9183VAP31053H0R4

However, there was a name transfer event: https://explorer.stacks.co/txid/0x79ad2a1a264d049f13842f0f055f0a40073488c74277fb4a899ec0355d13d8a6?chain=mainnet

The api shows this account: https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SP3JKC09PH0RH8G1XVT031J3E3S0GJ15DEMG7EAZP/assets does infact own the name.

This is likely an API bug that should be fixed when we have a new deployment, but cc @zone117x to be sure.

Once microblocks is launched on the api side, we should come back and confirm this is correct.

**Comment by fbwoolf** [comment]
Looking into this today, I seem to have the same issue in one of my accounts. This name transfer was successful, but it is still showing up in my wallet: https://explorer.stacks.co/txid/0x30a1a3d18709ddcd70ddb4fb904feeaf3cf5538aa724b7b5e78081fed6395ad0?chain=mainnet

Transferred from:
https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP2J1ZFZ5BYTD7H7F84CCZ2B4HEJSBV060XW79G1X

Transferred to:
https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP9CMJ7S8XR25H6ZKAJXT4M7KSPQ1B8PPVSYJRTC

**Comment by aulneau** [comment]
@zone117x any ideas?

**Comment by zone117x** [comment]
This seems like a possible bug. Can you open an issue in the API with these details?

**Comment by markmhendrickson** [comment]
@zone117x opened here: https://github.com/blockstack/stacks-blockchain-api/issues/714 🙏
